# Generated by Django 3.0.7 on 2020-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hsn',
            field=models.CharField(default='1212', max_length=30),
            preserve_default=False,
        ),
    ]
